# Repo info
owner: dangngocphuc
repo: uptime3

# Sites to monitor
sites:
  - name: BIDV
    url: https://bidv.com.vn

# Status website
status-website:
  baseUrl: /uptime3
  name: Uptime Monitor
  introTitle: "Website Monitoring Status"
  introMessage: "This page shows real-time uptime data powered by GitHub Actions."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dangngocphuc/uptime3
