owner: phucdn # GitHub username
repo: upptime3 # GitHub repository name
sites: # List of endpoints to track
  - name: tpbank
    url: https://tpb.vn
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website:
  baseUrl: /upptime3 # where "repo" is your repository name
  name: upptime3
